# Generated by Django 3.2.25 on 2024-03-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('uptime', models.CharField(max_length=100)),
            ],
        ),
    ]
